apiVersion: v1
kind: Secret
metadata:
  name: cstar-secret
type: Opaque
data:
  db_password: d2VsY29tZQ==
  pwd_scheme_01_salt: NzRmZWM5MmU5Njg2MjY0ZTM2MzcxODkxNjhlYjNjNTBmZmFh 
  pwd_scheme_02_salt: NzRmZWM5MmU5Njg2MjY0ZTM2MzcxODkxNjhlYjNjNTBmZmFh
  # For google OAuth, uncomment values below and set the value (base64 encoded)
  # google_oauth_client_id: __BASE64_ENCODEC_GOOGLE_CLIENT_ID__
  # google_oauth_client_secret: __BASE64_ENCODEC_GOOGLE_CLIENT_SECRET__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstar-config
data:
  https_mode: 'false'
  db_host: cstar-db-srv
  db_database: cstar_db
  db_user: cstar_user
  google_oauth_redirect_url: http://localhost:8080/goauth-redirect