apiVersion: v1
kind: Secret
metadata:
  name: cstar-secret
type: Opaque
data:
  db_password: d2VsY29tZQ==
  pwd_scheme_01_salt: NzRmZWM5MmU5Njg2MjY0ZTM2MzcxODkxNjhlYjNjNTBmZmFh 
  pwd_scheme_02_salt: NzRmZWM5MmU5Njg2MjY0ZTM2MzcxODkxNjhlYjNjNTBmZmFh
  pwd_prlink_salt: NzRmZWM5MmU5Njg2U0RGU0RXZGZlZmFlZWIzYzUwZmZhYQ==
  # For google OAuth, uncomment values below and set the value (base64 encoded)
  # google_oauth_client_id: __BASE64_ENCODEC_GOOGLE_CLIENT_ID__
  # google_oauth_client_secret: __BASE64_ENCODEC_GOOGLE_CLIENT_SECRET__
  service_ssl_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeUg5Qi9Sd1NmUWZYNkwwRGYyOE5VT2RReWRQanJUUFlJQ29OcC9CZlByc0JEQlJECkhqK0dveUN3Z05Pd1RhWXRQUWo5azVuNnd5aUo0TXg4VWM4U1MzTGFZRFdsaDh1NnJuTmIxWGxlZUFJYU5XQ3YKeVJyaUEvUlRzVDZWOWc1VklrU3B4OWdmTVc1SlMvL3cyekYxdjdhZm1hY3h5dmdxT1F6eGJTV29VMW1MZ3ZDMApDTFRZdlEwVG5uelNmb01xblpuUHZBOVJXWFFQUC9iSkVOQTVZTEdhbFdaV3U1eUZ3OFpBaGkrN0hsS0FoUU9CClNpSUxuK0ZnS3V2L2RqdnlTMlZsa1I5Y1EzQ29zWnJ6cWd3RytXMUxHSGtjL2g5VWNvbHFlc3ZqQmtJZGVlRXUKZlBvNHdwb3RYaVMwVXlDQWZZY21hUWxjOGIrZEFCdkVmZlhqQ3dJREFRQUJBb0lCQUhENkRIUVVtbkpydGdVRwpaTzhzNDRNQUpTemxRZmo2S3NITkVJN2VTcjB0WU9TdWtqZDhNbUMvYmRYWjh4RitIeVd5YURrQTNpV1VOVVUvCjFKbkFwaDF2cFkvckN0QmZRMTFEMGE2VHltQ3pScE5uWFFaa0tKRnozcWtVakNudlg1ZUV1MnJKNUtIVTlHWm4KM1ErV2FqUlNNdExCUExTVGJDOWpsTE1kTWlGc1oxS3h2bExuUjNUeHlEUTV1T3U4VGVoODdoR0U5R3pWRUREMApFL1NZODNQZGNTbG8vRUY1Q1pFdm9hbFVmNjRPbXh2c1RjQi82WXMrb0paK0pqK0M3ZXFqTE92bGZmVS9OeVgyCmxyWTNhSWZCU1NoaThMQmhPMzJOcHJ6VzV6aGJNTmYvM1g0WmR6NlVhc1ZoNVZDLzFiOVFKSzh2Y0tnbkNhNU4KWERDZGk4a0NnWUVBNmpRMlZya3hyRE8rSU1DdHhWa0YzQlBwc213MmlXdVVVSlhtZnZZa3p5KzJudXlkZmplMApBY1BzbEwwTlR3c1BNdEcxU25lM29aR3dBOFEwWkFQeElHK3pVTUxuWEF6Y3ZsaHl0cUIxd3lSY3BqbmFCcEhwCkZiSEFyZHZmQy9kWFNrVTJLdm5KUWJ5UG5VaWpCNW5UTTR5T2d0eUp4NEJBR09FUmxnRHMrQmNDZ1lFQTJ5Zi8KU05YVHNqYzhkWjF4a2IvdVRmRnZ5eUpkUlJ6YmNsY25BNUJydzBkUkZvWFBlM0p2NFg0ajNoN3RNSWZSdlJ5RgpHVXJDNlNTTVRJb2JwNks1K1piNTAyMWhNelZiUlA0bFY4K2dOdWNPTHdZdER4ZlhJczNIODVHeHJGT0Z5eDhYCkRJbllzNVl0cUlIekdFbGhWTXRpc0NEbkNwUjFuSEd0c2djSlVTMENnWUFsVGhIRnVKUC84UEg4OTVQMlZsckgKbG1ob0lqS0JxeUFod2U3SUZGOENuWUFDU29BL3BaSEhvalNoOEljWkt4TE5ybmVwRis2cERyS3h0dVA5ZGw5SApJbU8ybm9VSnRZYkh6d0RldENwdDNmSGdER0Q5SU9xMnFPeWZCT0cvWHpPSlFnTUJ6MjNPU2NHNmRPSjdDSGFLCnhIM0N2R3c1MmVUYjBhWGlkZDFKR3dLQmdDdGNtNWNtcjY4NFhKOE0ydGF5dWd6ejgyR20xL3QvdlMrL2JMbTQKem9taHg3cUVHVXhjbFNSeGw5a3dGMUFkMzNMaWZMZEhZbzlNcXZITjliRFNjcWVlcHFtZG43akpHdGpvekN5MgpxUVdUNit1RDlsQmhNRER6dEZkT0FYQ09TZytwaEI3MyswZDFORzE5NE1KeWFtNmptMUFzQW1yR2V3ck1OMGpkCk9ZdTFBb0dCQUpieFJvVm14d3dUT3lOVXdiWkwvSHpvcXVVWllUckE4THNyWWdFL0FzUTY3Y3lOZ0VTT0tua1kKb3pLZ21PODlSaEcvd2VMNnF0VVFDUlZTRnhUR2J5SUdPenp3eWJCTjg4T0RrOWtnQ1ZUMm8yU0pFVUNXUXhVVgpJZjNHVUU1eUZCYzhZUjQ1Kzl3bWtCaW9qSXU2b1hvREwyaDJMYVR2NE4xekF1azRSa1FlCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  service_ssl_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwRENDQVl3Q0NRRGRsUUxwV2VINkNUQU5CZ2txaGtpRzl3MEJBUVVGQURBVU1SSXdFQVlEVlFRRERBbHMKYjJOaGJHaHZjM1F3SGhjTk1qRXdNakkzTWpFMU5ETXhXaGNOTkRnd056RTBNakUxTkRNeFdqQVVNUkl3RUFZRApWUVFEREFsc2IyTmhiR2h2YzNRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURJCmYwSDlIQko5Qjlmb3ZRTi9idzFRNTFESjArT3RNOWdnS2cybjhGOCt1d0VNRkVNZVA0YWpJTENBMDdCTnBpMDkKQ1AyVG1mckRLSW5nekh4Unp4SkxjdHBnTmFXSHk3cXVjMXZWZVY1NEFobzFZSy9KR3VJRDlGT3hQcFgyRGxVaQpSS25IMkI4eGJrbEwvL0RiTVhXL3RwK1pwekhLK0NvNURQRnRKYWhUV1l1QzhMUUl0Tmk5RFJPZWZOSitneXFkCm1jKzhEMUZaZEE4Lzlza1EwRGxnc1pxVlpsYTduSVhEeGtDR0w3c2VVb0NGQTRGS0lndWY0V0FxNi85Mk8vSkwKWldXUkgxeERjS2l4bXZPcURBYjViVXNZZVJ6K0gxUnlpV3A2eStNR1FoMTU0UzU4K2pqQ21pMWVKTFJUSUlCOQpoeVpwQ1Z6eHY1MEFHOFI5OWVNTEFnTUJBQUV3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUtjZG5nM3JhVXFoCmFXZWpDT0lxc1hDdXltem15NjB6RW1pc25RUlB0a1JvVkIrbG52SGJ4WjZHZVY3Q2VBRytjTDUzV1dCOVVZNmkKNlRQZzJkc0x3T3FhYWl3MDB0UWtNZmVXR2FJRXVUY1luQ0tKOVFzZ2dFZHpxcHFaRVFWN3daK1YrbHBSaHlyTApwRHNuUzZ2L3FMUldYNlVoWCszN2FaVmdIWk1OMGJrR05ERWZBTTdTWmxPaG5BbGVhcFd1cU90SGIvaXQ0Mk93Ck92SDl3K3NQY0pKZEVMMUFHOUptYnJ4cEIzaWxwKzNFRHV5YmtZVkYzR0tHSks3YnR2S0I5OUF6Uy9kVkdHQjIKU0VFbHVkZ1ZucFNzZDk3YnllT1FMT1Z0K2ZQVUVOVjdwa2FzdFU4Mjc2a0M2RzdtVnBSS2ovdlhjM3p5dFdwWQo3Q2N2SnhxZTFtRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cstar-config
data:
  https_mode: 'false'

  # Core store credential (when mino)
  core_store_bucket_name: core-store-bucket
  core_store_access_key_id: AKIAIOSFODNN7EXAMPLE
  core_store_access_key_secret: wJalrXUtnFEMIKK7MDENGKKPxRfiCYEXAMPLEKEY
  # Core store info
  core_store_root_dir: core-store-root/

  # for dev only (points to kubernetes minio docker image). Comment when on S3
  core_store_minio_endpoint: http://cstar-mock-s3-srv:9000

  # Note: For dev. In prod, this will be the CDN url that will point to the core bucket backend.
  core_store_cdn_base_url: http://localhost:9000/core-store-bucket/

  # Database
  db_host: cstar-db-srv
  db_database: cstar_db
  db_user: cstar_user

  # Google
  google_oauth_redirect_url: http://localhost:8080/goauth-redirect