apiVersion: v1
kind: Secret
metadata:
  name: cba-secret
type: Opaque
data:
  db_password: d2VsY29tZQ==
  pwd_scheme_01_salt: NzRmZWM5MmU5Njg2MjY0ZTM2MzcxODkxNjhlYjNjNTBmZmFh 
  pwd_scheme_02_salt: NzRmZWM5MmU5Njg2MjY0ZTM2MzcxODkxNjhlYjNjNTBmZmFh
  # For google OAuth, uncomment values below and set the value (base64 encoded)
  # google_oauth_client_id: __BASE64_ENCODEC_GOOGLE_CLIENT_ID__
  # google_oauth_client_secret: __BASE64_ENCODEC_GOOGLE_CLIENT_SECRET__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cba-config
data:
  https_mode: 'false'

  # Core store credential (when mino)
  core_store_bucket_name: core-store-bucket
  core_store_access_key_id: AKIAIOSFODNN7EXAMPLE
  core_store_access_key_secret: wJalrXUtnFEMIKK7MDENGKKPxRfiCYEXAMPLEKEY
  # Core store info
  core_store_root_dir: core-store-root/

  # for dev only (points to kubernetes minio docker image). Comment when on S3
  core_store_minio_endpoint: http://cba-mock-s3-srv:9000

  # Note: For dev. In prod, this will be the CDN url that will point to the core bucket backend.
  core_store_cdn_base_url: http://localhost:9000/core-store-bucket/

  # Database
  db_host: cba-db-srv
  db_database: cba_db
  db_user: cba_user

  # Google
  google_oauth_redirect_url: http://localhost:8080/goauth-redirect