apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstar-admin-server-dep
  namespace: default
  labels:
    run: cstar-admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-admin-server
  template:
    metadata:
      labels:
        run: cstar-admin-server
    spec:
      volumes:
        # Those volumes are for development, it allow REPL dev from local build {{dir}}
        - name: cstar-admin-server-web-folder
          hostPath:
            path: '{{dir_abs}}/services/admin-server/web-folder'
            type: Directory
        - name: cstar-admin-server-src
          hostPath:
            path: '{{dir_abs}}/services/admin-server/src'
            type: Directory
        - name: cstar-admin-server-dist
          hostPath:
            path: '{{dir_abs}}/services/admin-server/dist'
            type: Directory
      containers:
        - image: "localhost:5000/cstar-admin-server:{{image_tag}}"
          name: cstar-admin-server-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cstar-config
            - secretRef:
                name: cstar-secret
          env:
            - name: service_name
              value: admin-server                    
          volumeMounts:
            - mountPath: /service/web-folder
              name: cstar-admin-server-web-folder
            - mountPath: /service/src
              name: cstar-admin-server-src
            - mountPath: /service/dist
              name: cstar-admin-server-dist
      restartPolicy: Always