# Note: here we do not need a k8s service since this service does not have any web/socket API (it connects to redis, but nobody connects to it)
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cba-agent
  name: cba-agent-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cba-agent
  template:
    metadata:
      labels:
        run: cba-agent
    spec:
      volumes:
        - name: cba-agent-src
          hostPath:
            path: '{{projectDir}}services/agent/src'
            type: Directory
        - name: cba-agent-sql
          hostPath:
            path: '{{projectDir}}services/agent/sql'
            type: Directory
        - name: cba-agent-dist
          hostPath:
            path: '{{projectDir}}services/agent/dist'
            type: Directory            
      containers:
        - image: 'localhost:5000/cba-agent:{{imageTag}}'
          name: cba-agent-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cba-config
            - secretRef:
                name: cba-secret
          env:
            - name: service_name
              value: agent          
          volumeMounts:
            - mountPath: /service/src
              name: cba-agent-src
            - mountPath: /service/sql
              name: cba-agent-sql
            - mountPath: /service/dist
              name: cba-agent-dist              
      restartPolicy: Always
