apiVersion: v1
kind: Service
metadata:
  labels:
    run: cba-db # we label run: ... all the resources that run a particular service (here cba-db)
  name: cba-db-srv # name will be the -... three letters abbreviation of the Kind
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: cba-db # this will select from the template.spec.metadata.labels (the pod)
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cba-db
  name: cba-db-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cba-db
  template:
    metadata:
      labels:
        run: cba-db
    spec:
      containers:
      - image: localhost:5000/cba-db:{{imageTag}}
        imagePullPolicy: Always
        name: cba-db-ctn
        env:
          - name: service_name
            value: db         
          # Default root postgres user password.
          # NOT FOR PRODUCTION!!!!! FOR DEV ONLY. In prod use cloud sql / rds. Set root password.
          - name: POSTGRES_PASSWORD
            value: 'postgres'        
        ports:
          - containerPort: 5432
            protocol: TCP
      restartPolicy: Always

