apiVersion: v1
kind: Service
metadata:
  labels:
    run: cstar-mock-s3 # we label run: ... all the resources that run a particular service (here cstar-mock-s3)
  name: cstar-mock-s3-srv # name will be the -... three letters abbreviation of the Kind
  namespace: default
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: cstar-mock-s3 # this will select from the template.spec.metadata.labels (the pod)
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cstar-mock-s3
  name: cstar-mock-s3-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-mock-s3
  template:
    metadata:
      labels:
        run: cstar-mock-s3
    spec:
      containers:
      - image: localhost:5000/cstar-mock-s3:{{imageTag}}
        imagePullPolicy: Always
        name: cstar-mock-s3-ctn
        env:
          - name: service_name
            value: mock-s3        
          - name: MINIO_ACCESS_KEY
            value: 'AKIAIOSFODNN7EXAMPLE'        
          - name: MINIO_SECRET_KEY
            value: 'wJalrXUtnFEMIKK7MDENGKKPxRfiCYEXAMPLEKEY' 
        ports:
          - containerPort: 9000
            protocol: TCP
      restartPolicy: Always

