apiVersion: v1
kind: Service
metadata:
  labels:
    run: cstar-queue
  name: cstar-queue-srv
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: cstar-queue # this will select from the template.spec.metadata.labels (the pod)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstar-queue-dep
  labels:
    run: cstar-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-queue
  template:
    metadata:
      labels:
        run: cstar-queue
    spec:
      # The host-sys volume and init containers are to disable the THP for redis. 
      # Will be disabled at the node level, but other services do not need THP to function properly. 
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
      initContainers: 
        - name: disable-thp
          image: busybox
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled"] 
      containers:
        - image: localhost:5000/cstar-queue:{{imageTag}}
          imagePullPolicy: Always
          name: cstar-queue-ctn
          ports:
          - containerPort: 6379
            protocol: TCP
      restartPolicy: Always