apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cba-vid-scaler
  name: cba-vid-scaler-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cba-vid-scaler
  template:
    metadata:
      labels:
        run: cba-vid-scaler
    spec:
      volumes:
        # Those volumes are for development, it allow REPL dev from local build
        - name: cba-vid-scaler-src
          hostPath:
            path: '{{projectDir}}services/vid-scaler/src'
            type: Directory
        - name: cba-vid-scaler-dist
          hostPath:
            path: '{{projectDir}}services/vid-scaler/dist'
            type: Directory
      containers:
        - image: localhost:5000/cba-vid-scaler:{{imageTag}}
          name: cba-vid-scaler-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cba-config
            - secretRef:
                name: cba-secret
          env:
            - name: service_name
              value: vid-scaler
          volumeMounts:
            - mountPath: /service/src
              name: cba-vid-scaler-src
            - mountPath: /service/dist
              name: cba-vid-scaler-dist
      restartPolicy: Always