apiVersion: v1
kind: Secret
metadata:
  name: cba-secret
type: Opaque
data:
  db-password: d2VsY29tZQ==
  # For google OAuth, uncomment values below and set the value (base64 encoded)
  # google_oauth-client_id: __BASE64_ENCODEC_GOOGLE_CLIENT_ID__
  # google_oauth-client_secret: __BASE64_ENCODEC_GOOGLE_CLIENT_SECRET__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cba-config
data:
  db-host: cba-db-srv
  db-database: cba_db
  db-user: cba_user
  google_oauth-redirect_url: http://localhost:8080/goauth-redirect