apiVersion: v1
kind: Service
metadata:
  name: cstar-web-server-srv
  labels:
    run: cstar-web-server
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:349642121055:certificate/777797eb-a8f6-4673-9f90-9155747d704f
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"    
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080      
  selector:
    run: cstar-web-server