# Note: here we do not need a k8s service since this service does not have any web/socket API (it connects to redis, but nobody connects to it)
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cba-agent
  name: cba-agent-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cba-agent
  template:
    metadata:
      labels:
        run: cba-agent
    spec:
      containers:
        - image: '{{registry}}cba-agent:{{imageTag}}'
          name: cba-agent-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cba-config
            - secretRef:
                name: cba-secret
      restartPolicy: Always
