apiVersion: v1
kind: Service
metadata:
  labels:
    run: cba-queue
  name: cba-queue-srv
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: cba-queue # this will select from the template.spec.metadata.labels (the pod)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cba-queue-dep
  labels:
    run: cba-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cba-queue
  template:
    metadata:
      labels:
        run: cba-queue
    spec:
      containers:
        - image: '{{registry}}cba-queue:{{imageTag}}'
          imagePullPolicy: Always
          name: cba-queue-ctn
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always