apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cstar-web-server
  name: cstar-web-server-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-web-server
  template:
    metadata:
      labels:
        run: cstar-web-server
    spec:
      containers:
        - image: '{{registry}}cstar-web-server:{{image_tag}}'
          name: cstar-web-server-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cstar-config
            - secretRef:
                name: cstar-secret
          env:
            - name: service_name
              value: web-server                
      restartPolicy: Always