apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cba-web-server
  name: cba-web-server-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cba-web-server
  template:
    metadata:
      labels:
        run: cba-web-server
    spec:
      containers:
        - image: '{{registry}}cba-web-server:{{imageTag}}'
          name: cba-web-server-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cba-config
            - secretRef:
                name: cba-secret
          env:
            - name: service_name
              value: web-server                
      restartPolicy: Always